### ISSUE TITLE
Open invitation to join weekly merge sub-committee meeting

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/bootstrap#10]
Hey All,

We have been having a weekly meeting with stakeholder from both the Node.js and JSF boards since we begun conversations about the intent to merge. After today's meeting we wanted to offer the timeslot to this group, specifically so that we could have a time for a meeting where collaborators from various projects and representatives of both foundations boards could collaborate.

One of the biggest pieces of feedback I took from the collaborator summit was that we don't want things to feel like they are happening in a black box, and it would seem to me that having a weekly meeting with all stakeholders is going to be our best option for reaching consensus in a transparent way.

The meetings take place every Monday at 2pm EDT (11 am PDT). While the meetings up until this point have been private, we would like to move them to be publicly broadcast and recorded on YouTube as we do with all other project meetings. We would also keep public notes.

Is this something that people participating in the bootstrap committee would be interested in? I know the governance, including meeting times, are just being fleshed out, but it seems like a great opportunity to take advantage of a timeslot that is already booked off on a large number of calendars. We regularly get 8 - 10 people in this meeting, with representation from the JSF board, the Node.js foundation board, and the Linux Foundation.

**Comment by MylesBorins** [comment]
Quick ping on this. If there are no objections I'm going to start getting this set up

**Comment by mcollina** [comment]
Count me in.

>

**Comment by chowdhurian** [comment]
^^ Likewise

**Comment by dshaw** [comment]
Count me in. Though my employment situation is about to change, so I may have to adjust when I get started.

**Comment by MylesBorins** [comment]
I've scheduled a meeting in zoom for next Monday

https://zoom.us/j/304274848

Will work with folks on getting an agenda together. The recurring time slot conflicts with the current "Individual Membership Subcommittee" meeting... I'll work with that team to see if we can clear that up. There is no conflict next week though, so we do have a bit of a buffer 🎉

**Comment by mhdawson** [comment]
Added to Node.js foundation calendar

**Comment by mhdawson** [comment]
I'll try to make it as well

**Comment by knolleary** [comment]
Thanks @MylesBorins - I will try to attend

**Comment by MylesBorins** [comment]
I've made a tentative agenda for monday and opened https://github.com/nodejs/bootstrap/issues/14

closing this issue. Please chime in on #14 with any thoughts or concerns
