### ISSUE TITLE
Governance Breakout Session Takeaways

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/bootstrap#11]
# Governance Breakout Session Takeaways

On Oct. 12th and 13th we hosted group Foundation Governance brainstorm sessions at the Collaborator Summit after Node+JS Interactive. The following are the contents of the sticky notes we plastered the conference walls with while ideating new joint Foundation Values and possible Programs.

## Values
We identified four major values from our session:

### Simplicity
- By-laws general enough not to require evolution
- Simple, project-driven governance evolution

### Transparency
- Open Governance
- Radical Collaboration (different than radical transparency)
- Data over opinions
- Right to disagree and target resolving disagreement in decision making

### Project Independence
- Value workers with large community on future direction – ex standards
- Ensuring health of highly used / critical libraries
- Recognition
- Championing new efforts
- Projects make all technical decisions
- Valuing project input for all decisions
- Make projects feel like a priority
- Ability to leave

### Community Focus
- Bring members together on a regular basis with equal accessibility
- Be less US / North American centric (engage with communities / developers worldwide)
- Global Leadership (not based in San Francisco)
- Value moral values
- Welcoming and community focus
- Diversity and Inclusivity with a global perspective.
- Diversity, inclusion, representation

## Programs
Programs that emerged from the session were grouped by the Foundation Value they most support. Programs would be administered by one or both of the Top Level Councils (CPC or C3). Each actionable program can conceivably go through the Program RFC Process defined in `/programs`[currently proposed in PR #7](https://github.com/nodejs/bootstrap/pull/7/files).

### Supporting Value: "Community Focus"

- Budget for inclusivity programs / initiatives
- Contributor Covenant
- 360 deg Reviews (programs, management, etc)
- Outline representative / leadership expectations
- Code and Learn continues
- Program for clean communication / escalation
- Facilitated Code of Conduct
- CoC / Docs support ("docs in a box")
- CoC Escalation Support
- Moderation
- Reward / Appreciation program for project contributors
- Support & engage community members who are doing un-glorious work
- Regional Chapters

### Supporting Value: "Transparency"
- Clear value proposition for Members
- OSS Grants program (needs basis)
- 3rd party grant application assistance
- Board + Project 1:1 Time
- Ticket Request System

### Supporting Value: "Simplicity"
- Easy evolution process for governance / process
- Program for Program Proposals
- Standards Process Assistance (education, up-leveling, funding for participation)

### Supporting Value: Project Independence
- Project Lifecycle
  - Requires well defined criteria for each step
  - Annual review of all projects
  - "Incubator" program for incoming projects
  - "Top-Level Projects" program for graduated projects
  - "Commons.js" program for non-top-level projects
  - "Hospice" care for older projects (What are the benefits?)
- Project collaboration as a program (?)
- Project presence on social media / ownership of social channels (federated account access)
- Comms assistance / promotion
- Infrastructure Support for Contracts / LSAs
- Project legal support

## Major Outstanding Questions

- What is the full project lifecycle story?
- What is the definition of a "Program"?
- How do we measure Foundation work?
- How does earmarking work?
- Can Individual Membership funds be earmarked?
- How do we measure the success of the Foundation?
- How do we measure the success of a Program?
- What are the non-goals of the Foundation?
- What is our scope? JS? Web? Tech? "A JS Angle"?
- What is the worst-case scenario Bootstrap vote model if full consensus can't be reached?

## Ideas on Bootstrap Group Functionality

- Temporary Merge Program Manager
- Bootstrap workgroup should serve the interest of the projects, not the board.
- Goal: Minimum Viable Foundation to vote on and move to
- What are the strategic objectives of the new org for Q1-Q4 2019?
- Don't bikeshed on the name for now.
- Perfect is the enemy of done.
- PREMATURE OPTIMIZATION IS THE ROOT OF ALL EVIL (yes, in all caps 😉)
- Design the flow of information through the org
- Publish the key roles & responsibility of the org (ED, CPC Chair, etc)

**Comment by amiller-gh** [comment]
Note: This is a GIANT issue with a lot of content – please be mindful of keeping the conversation simple here, and consider if your topic is best spun off into another issue, or in a program RFC where you can propose details about a specific topic! 🙂

**Comment by amiller-gh** [comment]
Ideally, we'll keep the conversation in this thread about how the breakout session went, or specifics about this transcription of sticky-note data.

**Comment by MylesBorins** [comment]
I believe that this has now been documented in the expectations proposal. Can we close this?

**Comment by amiller-gh** [comment]
Closed #42
