### ISSUE TITLE
How do we govern this group?

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/bootstrap#2]
Some questions we need to ask

* Do we have a team in github?
* ~~How do people request to join?~~
* ~~Membership requirements?~~
* How often / when do we meet?
* ~~Who can attend meetings?~~

edit: some more thoughts

* What is the process for landing changes into this repo

edit 2:

Crossed out items we have consensus on

**Comment by amiller-gh** [comment]
I'm +1 for a team in Github for easier management with the membership discussed in today's meeting.

**Comment by MylesBorins** [comment]
From Today's meeting:

Members in include

* Node.js Members: @nodejs/members
* JSF Project Maintainers
* JSF TAC
* Node.js Foundation Board of Directors
* JSF Board of Directors

All the above are invited to all meetings and to participate in this repo.

Remaining to reach consensus on

---

How often / when do we meet?

Currently we have a weekly planned for 2:00 pm EDT. We could do alternating times to be more inclusive of those in different time zones. We could do a doodle, but there are way too many folks to really figure this out, so I'll make a proposal.

Alternating between 2:00pm EDT and 9:00am EDT

This goes early enough that those in EU will likely be able to take the meeting one of the meeting within business hours and not making those on the west coast get up far too early (although 6am is kind of gross). Will make an issue specifically for this point

---

What is the process for landing changes into this repo:

Seemed we had consensus around a non-objection + time based process. I'll open another issue to capture this

**Comment by MylesBorins** [comment]
Closing as I've captured the majority of question in #19. Will open a new issue to discuss meeting times
