### ISSUE TITLE
How often / when do we meet?

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/bootstrap#21]
Currently we have a weekly planned for 2:00 pm EDT. We could do alternating times to be more inclusive of those in different time zones. We could do a doodle, but there are way too many folks to really figure this out, so I'll make a proposal.

Alternating between 2:00pm EDT and 9:00am EDT

This goes early enough that those in EU will likely be able to take the meeting one of the meeting within business hours and not making those on the west coast get up far too early (although 6am is kind of gross).

**Comment by mhdawson** [comment]
+1 from me.

**Comment by rubys** [comment]
What motivates the 9am time?  Currently that's 2pm in Ireland.  Going to 10am (or perhaps even 11am) would make things easier for west coast US.

**Comment by MylesBorins** [comment]
TSC current does 8am, 12pm, 5pm EDT

9am seemed to offer a good afternoon time for EU and a time for China and Japan in the evening (9pm, 10pm), midnight for Australia. While 8 am would serve Pacific region a bit better it seemed dar to early for West coast.

For those in EMEA and APAC do you have a preference? If no one speaks up perhaps we simply bump to 10am EDT and then iterate?

**Comment by jasnell** [comment]
The 2pm Eastern time is rather early in the morning for folks who may want to join from parts of Asia or Australia. Perhaps the same schedule as currently used for the TSC would work?

**Comment by MylesBorins** [comment]
@jasnell the 2pm EDT time is preferred for the moment as one of the times as a large number of board members from both the JSF and the Node.js foundation have it marked off on their calendars already.

@rubys I am waiting for us to reach some sort of consensus about an earlier time or get the go ahead from @dshaw or someone else from the individual membership group that we can replace their time slot... neither has happened yet

**Comment by MylesBorins** [comment]
Let's call the meeting for next week at 9am, if we have issues with people joining we can discuss and iterate. Expect a meeting issue to be opened v soon

**Comment by jasnell** [comment]
FWIW, 9am ET/6am PT on Mondays will generally not work for me do to a standing conflict.

Perhaps rather than selecting a time like this, we follow a similar kind of process that was used to select the TSC call times... that is, provide a google speradsheet where folks can indicate their generalized availability through the typical week and we iterate from there... and in the meantime, keep the 2pm ET call next week as was said on the previous call.

**Comment by MylesBorins** [comment]
@jasnell I've been informed by @dshaw that he can move the other meeting, so unless anyone objects lets move the meeting back to 2pm. Sorry about the back and forth, we have time on the agenda to discuss the timing lets lock down something during this meeting.

**Comment by ZibbyKeaton** [comment]
So we are aiming for 2pm ET on Monday, November 5. I want to make sure get this shared on social.

**Comment by mhdawson** [comment]
We also meet to add the meeting on the node.js calendar as I don't thin kit is there yet.

**Comment by MylesBorins** [comment]
Meeting times have been added to the calendar. We are indeed aiming for 2pm ET on Monday

**Comment by MylesBorins** [comment]
We had consensus in the last meeting to stick with the 9am and 2pm ET times for now.

It was brought up that a member of the LF team who is going to support us will be unable to joint for the 2pm ET time, are there any objection to moving that time to 1pm ET? Alternative times to suggest?

**Comment by mcollina** [comment]
9am ET is perfect for me, while 2pm ET is unfeasible.
Unfortunately today I have not been able to join because of the Node.js security release work.

**Comment by MylesBorins** [comment]
Agreement in today's meeting to keep the current alternating times.
