### ISSUE TITLE
Question for Legal Committee: Node.js Trademark

### ISSUE THREAD

**Issue by jasnell** [nodejs/bootstrap#25]
@hackygolucky @MylesBorins ... Can either of you please get an answer to the following question:

Is Joyent's grant to the management of the Node.js trademark *exclusive* to the Node.js Foundation? In other words, if the Node.js project decided to leave the current Foundation for any reason and move to a new similarly classed non-profit organization, could it negotiate it's own agreement with Joyent for use of the trademark?

I believe getting an answer to this question would be helpful in helping to address part of the reasons why Node.js top level contributors believe a board seat is required.

(forked from the discussion in https://github.com/nodejs/bootstrap/issues/17)

**Comment by rubys** [comment]
IANAL, but my understanding is that an exclusive trademark license is effectively an assignment, and if the trademark had been assigned to the foundation, I would have expected the wording of https://nodejs.org/static/documents/trademark-policy.pdf to be quite different.

From my perspective, the possibility that a third party could negotiate or outright purchase this mark from Joyent is concerning.

**Comment by MylesBorins** [comment]
I'm going to remove this from the agenda for now, please lmk if it should be re-added

**Comment by boneskull** [comment]
@MylesBorins were @jasnell's questions answered somewhere, or are we waiting for a response, or..?

**Comment by MylesBorins** [comment]
From the [last meeting](https://github.com/nodejs/bootstrap/blob/master/meetings/2018-10-29.md#discussion):

> * Goal is to not disrupt trademark agreement for Node.js with Joyent, don’t anticipate need to do anything. Working out if there is anything we need to do.
> * Question on Node.js trademark
It is non-transferrable without Joyent’s approval. Any change would require negotiation with Joyent.

**Comment by jasnell** [comment]
That doesn't quite answer the question but allows me to defer an answer...

> Is Joyent's grant to the management of the Node.js trademark exclusive to the Node.js Foundation? In other words, if the Node.js project decided to leave the current Foundation for any reason and move to a new similarly classed non-profit organization, could it negotiate it's own agreement with Joyent for use of the trademark?

I didn't say anything about "disrupting" the existing trademark agreement. I asked if the agreement was exclusive and if the Node.js project could negotiate it's own agreement with joyent if it became necessary to do so from the projects point of view.

Based on this, I can defer that yes, we could negotiate a new agreement with joyent independent of the foundation if it became necessary.

**Comment by boneskull** [comment]
@jasnell 	 can this be closed?
