### ISSUE TITLE
Drafting initial governance for merged foundation

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/bootstrap#33]
Please take a look at https://docs.google.com/presentation/d/1qUcvZz4wmQtwcWu9rWjxFNmWw5plD9-4_7mtvQvCegk/edit#slide=id.p which is a deck we can start to populate to brainstorm on what the structure of a merged foundation could look like. Once we do some iterations in the slides we can convert those to proposals that can move through our graduated system.

It currently outlines our most recent proposed structure:

* Board
* Cross Project Council (CPC)
* Cross Community Council (C3)
* Top-Level Projects
* Incubator
* Sandbox
* Commons.js

It also has a place for us to sketch out ideas regarding project lifecycle.

I'm adding the `bootstrap-agenda` item and think this is something we should focus a bunch of time into next Monday

**Comment by mcollina** [comment]
The document is not openly accessible.

**Comment by thefourtheye** [comment]
@mcollina The document was made public during the meeting today. So, it should be accessible now.

**Comment by MylesBorins** [comment]
Accidentally closed wrong issue

**Comment by MylesBorins** [comment]
Closing issue as we have the majority of specifics in proposals now

Great work y'all!
