### ISSUE TITLE
What does the CPC look like?

### ISSUE THREAD

**Issue by bnb** [nodejs/bootstrap#37]
In the 2018-11-19 meeting, we discussed the need to address what the CPC actually looks like – what it does do, what it _doesn't_ do, and so on – and identified that the shape of representation is more of an element of that.

As such, I've slightly tweaked the scope of this issue to provide a platform for that discussion in context of the CPC. So, what does the CPC consist of?

**Original Content:** Per the CommComm meeting, I wanted to kick off this discussion so that we could figure out how representation of projects and how membership in the CPC works.

**Comment by mcollina** [comment]
Before talking about representation, we need to clearly articulate the responsibilities of these groups

**Comment by jorydotcom** [comment]
I'd like to ask that the CommComm consider inviting JSF project leads to any brainstorming conversations about the CPC & C3's representation, responsibilities & so on. My concern is that there will be some ideas that really resonate and take off for the Node community, but don't necessarily jive with JSF projects (or, you will need to spend some significant time "reselling" ideas). Perhaps we can schedule some kind of cross-community brainstorm about purpose and scope?

**Comment by MylesBorins** [comment]
Is there a reason these discussions can't happen in the weekly team
meeting? This seems like an important thing for us to work on.

**Comment by bnb** [comment]
Just updated the issue with a slightly tweaked context 👍

**Comment by mhdawson** [comment]
Should have added the link earlier: 

https://github.com/nodejs/bootstrap/blob/master/proposals/mdawson-cpc-charter/CPC-Charter.md
and update:
https://github.com/nodejs/bootstrap/pull/65

**Comment by mhdawson** [comment]
Discussed in last meeting, agree to close.
