### ISSUE TITLE
Related Project Monikers

### ISSUE THREAD

**Issue by obensource** [nodejs/bootstrap#44]
# Description
Right now the potential structure of the NodeJS+JSF Governance Structure (Stage 0) describes three entities for Projects that are supported by, or related to this organization:
* Incubator
* Sandbox
* Commons.js

### Incubator
"An official process for a project to become a project and get representation in CPC. Mentorship from CPC + CommComm." – Entities that are 'on their way' to becoming a top-level project.

### Sandbox
"A place for projects to live that want to benefit from being in the foundation but do not intend to graduate to a Top Level Project." – A 'neighboring' project that supports and is supported by the foundation.

### Commons.js
"Resources and initiatives available to non-foundation projects. CI, travel scholarships, mentorship, etc." – Initiatives and/or projects that revolve around and affect/are affected by the foundation.

# Problem
During a recent [Joint Foundation Bootstrap Meeting](https://github.com/nodejs/bootstrap/issues/39), the consensus was against these names as representative monikers for those entities, and we need to find ones that represent what they are well.

# Resolution
Let's come up with great names for these entities! 🙌

**Comment by jorydotcom** [comment]
We should also add "Graduate" or "Top Level Project" as monikers to iterate on - I've seen those used interchangeably in various places!

**Comment by bnb** [comment]
We may also want to include "Constellation Project" since this is something that does seem to be coming up, though I'd want other's +1s on adding it before it is added 👍

**Comment by mhdawson** [comment]
Just throwing out ideas but maybe: 
* Basic Member Project
* Incubation Member Project
* Full Member Project
* Constellation Member Project

To replace sandbox, incubating, top level and constellation.

**Comment by mhdawson** [comment]
One reason we need to define "Constellation Member Project"  I was interpreting it as a major project like Kubernetes/Node.js around which other projects form a Constellation.  In that context the Constellation projects are those that might get their own board set etc.

**Comment by jorydotcom** [comment]
There's something about the current monikers that are slightly confusing to me, and I wonder if this disambiguation makes sense:

**Commons.js** is a proposed _program_ that provides foundation resources such as a travel grant etc. or  to _any_ open source project, via some process developed and overseen by a $foundation committee. The exact services available are dependent on the budget and discretion of that committee. 

**Sandbox, Incubation, Top Level, and Constellation** are proposed _designations_ given to projects that have been accepted into the foundation based on their lifecycle and some TBD metrics. 

If that's the correct (read: everyone else's) understanding, I propose we focus this issue on the designations and table discussion of the programs until we're much farther along as the program doesn't have direct implications for the bylaws.

**Comment by MylesBorins** [comment]
Has this discussion been reflected in the project progression proposal? Can we close this issue?

**Comment by MylesBorins** [comment]
Closing this as we have landed the majority of these changes and have another issue to dig into the commons
