### ISSUE TITLE
New Bootstrap Team

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/bootstrap#46]
Hey All,

I just made a boostrap team so people can have proper write access to this repo.

If there are no objections I'll add everyone who has so far attended a meeting.

Raise your hand if you would like to join.

**Comment by obensource** [comment]
✋ Thank you @MylesBorins! 💯

**Comment by MylesBorins** [comment]
I've attempted to add everyone who has attended a meeting (specifically those who included their github data). If anyone else would like to join the team please chime in.
