### ISSUE TITLE
Meeting to discuss Project Progression Proposal

### ISSUE THREAD

**Issue by jorydotcom** [nodejs/bootstrap#69]
**UPDATE:**

Date/Time: Monday, January 14 @ 12:00 p.m. EST
Agenda Link: https://docs.google.com/document/d/1JWfz34vBeTrdMGCkS20a3mi5z_QTN1sZvPW3-AyDZMc/edit?usp=sharing
Zoom Link: 
> Please click the link below to join the webinar: 
> https://zoom.us/j/852050362
> 
> Or iPhone one-tap :
>     US: +16465588656,,852050362#  or +16699006833,,852050362# 
> Or Telephone:
>     Dial(for higher quality, dial a number based on your current location): 
>         US: +1 646 558 8656  or +1 669 900 6833  or +1 855 880 1246 (Toll Free) or +1 877 369 0926 (Toll Free)
>     Webinar ID: 852 050 362
>     International numbers available: https://zoom.us/u/aeaFiskhPe

---

On today's call we discussed having a separate working session to address some of the open issues on the project progression proposal.

@mcollina, it would be especially helpful for you to be there as you have had more targeted feedback. 

I'm suggesting Monday, January 14 at 9 a.m. for a call time - does that work for those interested? cc @bnb @brianwarner

**Comment by mcollina** [comment]
I'll be in Bangalore for a business trip.
I can potentially join the 9am EST call/14:00 UTC should work.

**Comment by MylesBorins** [comment]
9 am et/

**Comment by boneskull** [comment]
I'd like to join in, but would need a later time.

**Comment by mcollina** [comment]
It might be easier for me 1 or 2 hours later.

**Comment by brianwarner** [comment]
Any time on Monday is good for me.  I'll move things around as necessary.

**Comment by mhdawson** [comment]
Monday morning EST works for me at this point.

**Comment by jorydotcom** [comment]
@mcollina @boneskull would 11 a.m. EST work better?

**Comment by boneskull** [comment]
I could do 12 eastern, but otherwise will have to pass

**Comment by mcollina** [comment]
I can do 12 eastern.

**Comment by MylesBorins** [comment]
I can also do 12

**Comment by jorydotcom** [comment]
12 EST it is! I'll update the post with the date/time, @brianwarner can you hook us up with a zoom link?

**Comment by MylesBorins** [comment]
I've gone ahead and added it to https://nodejs.org/calendar

Here the joining instruction

> Hi there, 
> 
> You are invited to a Zoom webinar. 
> When: Jan 14, 2019 12:00 PM Eastern Time (US and Canada)
> Topic: Joint Foundation Project Proposal Discussion 
> 
> Please click the link below to join the webinar: 
> https://zoom.us/j/852050362
> 
> Or iPhone one-tap :
>     US: +16465588656,,852050362#  or +16699006833,,852050362# 
> Or Telephone:
>     Dial(for higher quality, dial a number based on your current location): 
>         US: +1 646 558 8656  or +1 669 900 6833  or +1 855 880 1246 (Toll Free) or +1 877 369 0926 (Toll Free)
>     Webinar ID: 852 050 362
>     International numbers available: https://zoom.us/u/aeaFiskhPe

**Comment by jorydotcom** [comment]
Thank you @MylesBorins!!

**Comment by jorydotcom** [comment]
hello all, we are just waiting for the meeting host to start the webinar.

**Comment by mcollina** [comment]
I'll start it then!

**Comment by jorydotcom** [comment]
thanks for a great meeting everyone - I'll send a PR to add the meeting notes in a bit.

**Comment by jorydotcom** [comment]
Meeting ended + Notes added to the repo, so this issue can be closed.
