### ISSUE TITLE
Define 'Open Governance' requirements for Top Level Projects

### ISSUE THREAD

**Issue by jorydotcom** [nodejs/bootstrap#74]
In summary from the Project Progression meeting this morning, the attendees are in general agreement that Open Governance should be a core value of top level projects. 

The suggestion is to start with the JSF's Mentorship Program as a jumping off point (copied below, linked [here](https://github.com/JSFoundation/TAC/blob/master/Project-Lifecycle.md#mentorship)

> ## Mentorship
> 
> The purpose of mentorship is to support and mentor projects entering the
> Foundation. The goal is for projects to be:
> 
> * Participatory
> * Transparent
> * Effective
> 
> While certain processes are strongly recommended based on the experiences of the
> Foundation and its Projects, the goal of mentorship is not to enforce a specific
> set of processes but to ensure that the processes adopted and accepted by a
> project achieve these goals. Therefore, the requirements for graduating from
> mentorship are based on metrics that demonstrate success in terms of these
> values. These metrics are:
> 
> * Project's defined governing body is 5 members or greater
> * No more than 1/3 of the defined governing body is affiliated with the same
> employer.
> * No more than 1/3 of any Project is affiliated with the same employer.
> * The decision making and release process is documented and publicly accessible.
> * Other metrics as defined by the applying Project during the application
> process in cooperation with their mentor
> 
> A Project may apply to graduate from mentorship at any time by calling for a
> vote in the TAC.
> 
> While a Project is under mentorship, it is assigned at least 1 [mentor][] who
> is responsible for working with the Project to adopt policies and gain the
> health and contributorship it will need in order to graduate from mentorship.
> The mentor list is nominated and approved by the TAC and may be larger than the
> TAC.
>

**Comment by mcollina** [comment]
I am ok in using the requirements of a Graduated project for our top-level projects:

* Project's defined governing body is 5 members or greater
* No more than 1/3 of the defined governing body is affiliated with the same
employer.
* No more than 1/3 of any Project is affiliated with the same employer.
* The decision making and release process is documented and publicly accessible.
* Other metrics as defined by the applying Project during the application process in cooperation with the CPC.

**Comment by dylans** [comment]
“No more than 1/3 of any Project is affiliated with the same employer.”

Could we please elaborate on how this is defined? Is a project lines of code ever or over some amount of time, number of contributors, # of contributions over some amount of time, or some other formula.

**Comment by mhdawson** [comment]
Hmm, I agree with @dylans question.  

`No more than 1/3 of the defined governing body is affiliated with the same
employer.` is easy to quantify while `No more than 1/3 of any Project is affiliated with the same employer`.  

I think we should keep the governing body part and drop the second one. I think the first is a good metric of if there is open governance.  The second less so and can be problematic at a point in time as contribution for individuals/companies will vary over time with peaks and valleys.

**Comment by dmethvin** [comment]
Yeah I think the *governing body* part is the best measure. There may be times when a company is willing to dedicate resources to a project and ends up with a lot of PRs that skew contributions in some time frame. 

It's important IMO for a project's governing body to continue to have active participants beyond a single company. So that brings up the possibility that a top-level project might become non-top-level if they stop meeting the criteria at some point. When you think about a project lifecycle it seems very reasonable for that to happen. For example, RequireJS was *the* loader a decade ago but now is in maintenance mode and not a lot of that is needed.

**Comment by mcollina** [comment]
I agree with the "governing body" definition.

**Comment by jlipps** [comment]
👍 to "governing body" definition. the combination of 5 members and the 1/3 restriction means that each of the 5 will have to come from a different company (because 2/5 = 0.4 > 1/3). It might be difficult for some newer projects to have 5 different companies (or individuals) represented in their governance, but on the whole feel that it's a reasonable goal and requirement for being a TLP.

**Comment by mcollina** [comment]
@jlipps I think we should allow to have 2/5. Something like:

> No more than 1/3 of the defined governing body (rounded by excess) is affiliated with the same employer.

In that case, a single employer can have 2.

**Comment by jlipps** [comment]
@mcollina I'm also fine special-casing 5 members, as I think 2 from the same company will be a common occurrence early on, and 2/5 doesn't seem that bad to me (can't control outcome via a vote). So I'm +1 to your proposed language (I hadn't heard the phrase "rounded by excess" before and assume it means just what we're talking about).

**Comment by MylesBorins** [comment]
As #88 has landed I think this can be closed.  Feel free to re-open or let me know that I should if this was closed prematurely
