### ISSUE TITLE
Clarify Intentions around Project Codes of Conduct

### ISSUE THREAD

**Issue by jorydotcom** [nodejs/bootstrap#75]
In our project progression meeting this morning, we identified a gap in process/definition of expectations for codes of conduct. Specifically:

* do we allow projects to bring in their own codes of conduct, or require acceptance of our foundation CoC?
* where in the foundation is a 'CoC enforcement/support' team chartered?
* what is the expectation for that group in terms of enforcement of the CoC (proactive vs reactive monitoring for example)?

**Comment by chowdhurian** [comment]
> do we allow projects to bring in their own codes of conduct, or require acceptance of our foundation CoC?

A big value of a Foundation is good docs-in-a-box: tried and tested docs that can be used with minimal setup time/effort.

I wonder what the reason for bringing one's own CoC would be.

> what is the expectation for that group in terms of enforcement of the CoC (proactive vs reactive monitoring for example)?

Proactive monitoring looks restrictively resource-intensive. Being looped in in the event of a failure to self-moderate seems a good balance of project autonomy and resources.

**Comment by jorydotcom** [comment]
I'm a strong supporter of not only having a foundation-wide CoC, but also having that be something that any project can adopt. Further, I'm in favor of the foundation hosting group that *is available to support projects in their CoC enforcement efforts.* As @mcollina says, if there is a situation that the project team can't manage for some reason, or there is an issue that involves project leadership, then the foundation team could be called to help. It could also be asked to provide advice. 

> do we allow projects to bring in their own codes of conduct, or require acceptance of our foundation CoC?

The JSF hasn't had a project bring its own CoC but it does allow the option. I'm not sure how much of an issue this really is for potential projects; if the CoC we adopt is as straightforward as say the contributor covenant, I imagine there wouldn't be a problem making adoption of the Foundation CoC a requirement.

> where in the foundation is a 'CoC enforcement/support' team chartered?

I'd support this being a standing CPC committee, and also ensuring that we're able to bring in folks with moderation experience + skills

**Comment by mhdawson** [comment]
+1 to
>I'm a strong supporter of not only having a foundation-wide CoC, but also having that be something that any project can adopt. Further, I'm in favor of the foundation hosting group that is available to support projects in their CoC enforcement efforts. 

In terms of CoC I could see us having a base CoC but there might be a project that wants something "more" stringent and it could make sense to accommodate that case (but not the less stringent case)

**Comment by nzakas** [comment]
Part of the benefit I saw with joining JSF was to have an already-vetted CoC written up complete with an established CoC complaint process that could happen outside of the ESLint team (which is important should the violator be a member of the team). For those reasons, I'm in favor of a Foundation-wide approach to CoCs.

**Comment by mhdawson** [comment]
For reference this is where the proposed approach is being discussed: https://github.com/nodejs/bootstrap/pull/80

**Comment by MylesBorins** [comment]
As #80 has landed I'm going to close this. Feel free to re-open or let me know that I should if this was closed prematurely
