### ISSUE TITLE
Conflict for Next meeting 2019-01-21

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/bootstrap#78]
Hey All,

It appears the next meeting has a conflict with MLK Jr. Day in the united states which is a federal holiday. Wanted to get a pulse for who would still be able to attend. Can you respond to this post with emoji so we can get an idea if we should cancel the meeting

👍🏽 ~ I'll Make it
👎🏽 ~ I can't Make it

**Comment by chowdhurian** [comment]
This next meeting is at 14:00 UTC?

**Comment by mcollina** [comment]
I’m +1 in canceling as I will be on the road.

**Comment by mhdawson** [comment]
I can make it, no holiday for me :(

**Comment by MylesBorins** [comment]
Might be a small group, but lets do it!

Meeting agenda on route
