### ISSUE TITLE
Seek to understand and resolve foundation bylaw differences

### ISSUE THREAD

**Issue by rubys** [nodejs/bootstrap#8]
At the moment this is a work in progress.  As work progresses, updates will be posted here so people can follow its progress.

I'm starting by resolving formatting differences in the [JS Foundation Bylaws](https://github.com/rubys/bootstrap/blob/jsfoundation-bylaws/bylaws.md) and the [Node.JS Foundation Bylaws](https://github.com/rubys/bootstrap/blob/nodejs-bylaws/bylaws.md).  HTML formatted diffs of the results will be posted, and summaries of those diffs will be provided.

Obligatory disclaimer: anything we produce will need to be vetted, and potentially completely rewritten, by lawyers.  That being said, a firm understanding of what does and does not belong in bylaws, and furthermore, a deep understanding of the two starting points will be invaluable in preventing much wasted effort and misunderstandings.

Examples of very early results (from the first ARTICLE):

  * The names of the foundations are different (duh!)
  * The principle offices are on different streets in San Francisco.
  * The section on Additional Offices are identically worded.
  * The section on Purpose should inform our discussion on [Mission](https://github.com/nodejs/bootstrap/pull/4) and [Vision](https://github.com/nodejs/bootstrap/pull/1)
  * The JS Foundation has sought and obtained an exception from Federal Taxes, the Node.JS foundation has not (yet?) done so.

Outside of Section 4 ("Purpose"), there is little in ARTICLE I that will likely concern us.  This will change as we get to later sections.  Board representation (as explored in, for example, https://github.com/nodejs/bootstrap/pull/6) has direct bylaws implications.

**Comment by mhdawson** [comment]
@rubys I was thinking that looking at the 2 existing set of bylaws and potentially building a draft with the 2 as a basis would make the feedback we need to provide on this front much more concrete.  Thanks for doing this and looking forward to the coverage for the rest of the articles.

**Comment by rubys** [comment]
@mhdawson I'm envisioning a three pass process.  First pass is "what are the salient differences"? Second pass is a global triage on the differences.  As I alluded to above, my sense is that we very much care what the PURPOSE of the new foundation is, but don't particularly care where the principle office is.  A third pass would be to create a draft document, likely with plenty of TBDs (things we need to work) and EDONTCAREs (things that can be left to others).  The third pass will go quickly if the issues are largely independent (as the PURPOSE and principle office are), and if there isn't much desire to use this as an opportunity to address issues unrelated to the merge.  The flip of this is also true: if the issues are thorny and interrelated, and/or if there is a desire to inject other requirements into the process, this can take longer.

**Comment by rubys** [comment]
Article III major differences:
  * minor differences only in section 1 (JS foundation mentions Workgroups, Node specifies electronic notices)
  * no differences in nomination and election procedures

Article IV major differences:
  * Node specifies that no Director can speak for the foundation without authorization.
  * Each foundation has different, and complex, rules for keeping the ratio between Gold and Platinum members in check
  * Additional (different, complex) rules for keeping the ratios in sync, including (for node.js) provisions for "in good standing".
  * "good standing" differences only for enlargement/reduction
  * nearly equivalent rules for resignation and removal
  * nearly equivalent rules for vacancies
  * Identical "place of meetings"
  * JS Foundation allows "regular" meetings to occur "without notice".  Node only provides for scheduled meetings.
  * Essentially identical "special meetings" provisions
  * Supermajority vote is required in the node foundation for changing IP rules
  * essentially equivalent "action by consent"
  * telephonic meetings is split out to a separate section in the JS Foundation
  * identical "inspection rights"
  * in fees and compensation, JS Foundation says no "reimbursements", and Node.js says no "compensation".

**Comment by rubys** [comment]
Article V major differences:

* 5.1 of the JSF is split into two sections in Node.js; key differences being that the Node.js foundation explicitly disallows committees from taking actions that require a board vote, and provides a means for Platinum members to object to the board placing a member on a committee.
* Meetings of Committees of the Board are identical
* Node.js clarifies that term of offices is established at the time of the Election _as director_.
* Node.js mentions the TSC explicitly in the bylaws as a committee, and the JSF mentions a TAC.  Their roles are specified differently, most notably TAC has a role and is largely responsible for creating project and terminating projects.  JSF explicitly allows committees to have sub-committees, working groups, and special interest groups.

Article VI
* The Node foundation has a Chairperson and a Vice chairperson, both of which are required to be a Platinum Director.  The JSF has a President and one or more Vice presidents each of which is required to be a Director.  The JSF has a rule that no two Officers may be employed by the same Company, unless there are fewer than four Directors at such time.
* Vacancies is identical.
* Election differs only in the naming of the chair/president roles, and that the JSF includes ED and Treasurer in the annual election.
* Tenure is identical.
* The role of Chairperson in the node foundation is identical to the role of the President in the JSF.
* The role of the Vice Chair in the node foundation is identical to the role of the Vice Presidents in the JSF.
* The role of the Secretary is identical
* The role of the Assistant Secretaries is identical
* The JSF defines a Treasurer role
* Compensation differs.  In the Node foundation, no officer other than an ED can receive compensation; there is no such limit in the JSF.  In fact, the JSF goes further and says that being a Director doesn't preclude an individual from receiving a salary as an Officer.

**Comment by rubys** [comment]
Article VII

* Where the JSF uses "address", the NF uses "physical, email or telecopy address or number"
* Waver is identical

Article VIII

* Only difference in this entire article is in section 8.4, in the JSF determination of indemnification to be made by either a majority vote of the Directors who were not involved OR by the members; in the NF it is only by the Directors.

Article IX

* Only difference is a wording change in 9.5: "Delaware General Corporation Law" vs "General Corporation Law of Delaware".

Article X

* Only difference is a capitalization change in 10.1: "...in which one or more of its directors or officers are Directors or Officers" (NF) vs all lower case (JSF).

Article XI

* Section 11.1, JSF uses "Purposes" where the NF uses "Purpose".
* Section 11.2 Chairperson is subject to standing limits by the board (NF), where this isn't stated for the President (JSF)

Article XII

* Section 12.1, Fiscal year initially ended on December 31st (NF) and was not specified in JSF.
* Section 12.4, Membership is capitalized in NF, it is not in the JSF version

Article XII

* President vs Chairperson
* any division vs division
* Bylaws vs By-laws
* Purposes vs Purpose
* open source vs Open Source
* "code base, specification or platform developed or adopted by an Project" (JSF) vs "Platform developed or adopted by the $FOUNDATION"

Article XIV

* In addition to changing the bylaws by a supermajority vote of the board of directors, the JSF provides the ability for a change to be approved by 2/3 of the members, and further adds that members initiated changes happen at annual meetings, and in the case of Directors initiated changes it needs to be in the notice of the meeting

**Comment by rubys** [comment]
[HTML Diff](https://intertwingly.net/tmp/bylaws-diff.html).  Note that I didn't work in all cases to produce a minimal diff; I often stopped working on an article or section when the differences were clear and moved on.

**Comment by MylesBorins** [comment]
From today's meeting

Sections of bylaws that merit a lot of attention include:

* composition of board
* composition of committees
* what it takes to amend bylaws
* how decisions are made
* different classes of members and who/how gets on the board

**Comment by MylesBorins** [comment]
I'm going to remove this from the agenda for now, please lmk if it should be re-added

**Comment by MylesBorins** [comment]
Can this be closed?

**Comment by mhdawson** [comment]
It was mentioned that the lawyers have a current "merge" of the 2 as a basis for work going forward.  Maybe we can share a reference to that and then close this?
