### ISSUE TITLE
Name of $Foundation

### ISSUE THREAD

**Issue by brianwarner** [nodejs/bootstrap#84]
Now that we're making good progress on the other topics, it's a good time to think about proposing a name for $Foundation.

I propose we meet separately to discuss this, since naming can be a time consuming process and we don't want to derail the progress being made in the main bootstrap discussions.

If you want to participate, +1 this issue and I'll add you to my list.  When we get critical mass (hopefully in a few days or so), I'll work with you to find a good time for a call.

I can say with 100% confidence the outcome of this discussion will be one of the following:
- Use the Node.js Foundation name for the merged entity
- Use the JS Foundation name for the merged entity
- Come up with something new that's more appropriate

...I just can't say which one it'll be.  So let's discuss and put together a proposal!

**Comment by joesepi** [comment]
For what its worth, I own JavaScriptEtc.com :)

**Comment by brianwarner** [comment]
Per discussion in today's bootstrap call, let's have a separate call to talk some options.  To get a sense of time zones and general availability, please let me know if you can make any of these times: https://doodle.com/poll/gza7ed6bawewx7gn

**Comment by MylesBorins** [comment]
Closing as this has been decided 🎉

**Comment by ljharb** [comment]
@MylesBorins what's the name?

**Comment by jakeNiemiec** [comment]
> what's the name?

@ljharb "Open JS Foundation" https://youtu.be/DLzh65FrZEg?t=402

**Comment by knolleary** [comment]
The formal announcement hasn't been made yet - despite it being discussed in a meeting that was broadcast on youtube 😉So please keep this quiet until you see the proper announcement from the Foundation.
